# Generated by Django 2.0 on 2017-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
