# Generated by Django 2.0 on 2018-01-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
