# Generated by Django 2.0 on 2017-12-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20171206_1550'),
        ('register', '0002_auto_20171208_1131'),
    ]

    operations = [
    ]
