# Generated by Django 2.0 on 2018-01-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_verificationtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
