# Generated by Django 2.0 on 2017-12-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kategorie', models.CharField(max_length=100)),
                ('unterkategorie', models.CharField(max_length=100)),
                ('hersteller', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('notiz', models.TextField(max_length=500)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
