# Generated by Django 2.0 on 2018-01-28 15:19

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Datarow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='unit')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='description')),
                ('timerow', models.IntegerField(null=True, verbose_name='timerow')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='manufacturer')),
                ('typ', models.CharField(max_length=100, verbose_name='type')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('visibility', models.BooleanField(default=True, verbose_name='visibility')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_category_set', to='projects.Category', verbose_name='category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_subcategory_set', to='projects.Category', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=apps.projects.models.project_image_path, verbose_name='path')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True, verbose_name='value')),
                ('datarow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Datarow', verbose_name='datarow')),
            ],
        ),
    ]
