# Generated by Django 2.0 on 2018-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='measured',
            field=models.DateTimeField(null=True, verbose_name='measured'),
        ),
    ]
