# Generated by Django 2.0 on 2017-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_hersteller_kategorie_typ_unterkategorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hersteller',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.DeleteModel(
            name='Typ',
        ),
        migrations.DeleteModel(
            name='Unterkategorie',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='kategorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='notiz',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='hersteller',
            new_name='producer',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='unterkategorie',
            new_name='subcategory',
        ),
    ]
