# Generated by Django 2.0 on 2018-01-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datarow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='project_imageID',
            new_name='project_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='projects.Category'),
        ),
    ]
