# Generated by Django 2.0 on 2017-12-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171209_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_category_set', to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_subcategory_set', to='projects.Category'),
        ),
    ]
