# Generated by Django 2.0 on 2019-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180517_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='data_format',
            field=models.IntegerField(null=True, verbose_name='data_form'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='data_type',
            field=models.IntegerField(null=True, verbose_name='data_type'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='function_type',
            field=models.IntegerField(null=True, verbose_name='func_type'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='reference_dir',
            field=models.IntegerField(null=True, verbose_name='ref_dir'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='reference_name',
            field=models.CharField(max_length=10, null=True, verbose_name='ref_name'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='reference_node',
            field=models.IntegerField(null=True, verbose_name='ref_node'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='response_dir',
            field=models.IntegerField(null=True, verbose_name='res_dir'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='response_name',
            field=models.CharField(max_length=10, null=True, verbose_name='res_name'),
        ),
        migrations.AddField(
            model_name='datarow',
            name='response_node',
            field=models.IntegerField(null=True, verbose_name='res_node'),
        ),
    ]
