# Generated by Django 2.0 on 2019-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='data_format',
            field=models.CharField(max_length=20, null=True, verbose_name='data_form'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='data_type',
            field=models.CharField(max_length=10, null=True, verbose_name='data_type'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='function_type',
            field=models.CharField(max_length=40, null=True, verbose_name='func_type'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='reference_dir',
            field=models.CharField(max_length=20, null=True, verbose_name='ref_dir'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='response_dir',
            field=models.CharField(max_length=20, null=True, verbose_name='res_dir'),
        ),
    ]
