# Generated by Django 2.0 on 2018-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_experiment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='description',
        ),
        migrations.AddField(
            model_name='experiment',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
