# Generated by Django 2.0 on 2018-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180104_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='timerow',
            field=models.IntegerField(null=True),
        ),
    ]
