# Generated by Django 2.0 on 2018-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180113_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
