# Generated by Django 2.0 on 2018-01-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_datarow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
