# Generated by Django 2.0 on 2018-01-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180120_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
