# Generated by Django 2.0 on 2018-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180120_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
