# Generated by Django 2.0 on 2018-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180120_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='measuring_instrument',
            field=models.CharField(choices=[('Se', 'Sensor'), ('Ac', 'Aktor'), ('No', 'none')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='measured',
            field=models.DateTimeField(null=True),
        ),
    ]
