# Generated by Django 2.0 on 2018-01-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180125_1614'),
        ('projects', '0016_auto_20180124_1328'),
    ]

    operations = [
    ]
