# Generated by Django 2.0 on 2018-01-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_merge_20180125_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='measuring_instrument',
        ),
        migrations.AddField(
            model_name='datarow',
            name='measuring_instrument',
            field=models.CharField(choices=[('Se', 'Sensor'), ('Ac', 'Aktor'), ('No', 'none')], default='No', max_length=2),
        ),
    ]
