# Generated by Django 2.0 on 2018-01-27 23:43

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20180127_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='measuring_instrument',
            field=models.CharField(choices=[('SENSOR', 'Se'), ('ACTUATOR', 'Ac'), ('NONE', 'No')], default=apps.projects.models.MeasurementInstruments('No'), max_length=2),
        ),
    ]
