# Generated by Django 2.0 on 2018-01-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20180127_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='timerow',
            field=models.IntegerField(null=True, verbose_name='timerow'),
        ),
        migrations.AlterField(
            model_name='value',
            name='datarow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Datarow', verbose_name='datarow'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True, verbose_name='value'),
        ),
    ]
