# Generated by Django 2.0 on 2018-02-02 09:47

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180128_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarow',
            options={'verbose_name': 'datarow', 'verbose_name_plural': 'datarows'},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'experiment', 'verbose_name_plural': 'experiments'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'project image', 'verbose_name_plural': 'project images'},
        ),
        migrations.AlterField(
            model_name='datarow',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='measuring_instrument',
            field=models.CharField(choices=[('SENSOR', 'Se'), ('ACTUATOR', 'Ac'), ('NONE', 'No')], default=apps.projects.models.MeasurementInstruments('No'), max_length=2, verbose_name='measuring instrument'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='unit',
            field=models.CharField(max_length=10, null=True, verbose_name='unit'),
        ),
    ]
