# Generated by Django 2.0 on 2017-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171206_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firma',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
