# Generated by Django 2.0 on 2017-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
