# Generated by Django 2.0 on 2017-12-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.CharField(max_length=255),
        ),
    ]
