# Generated by Django 2.0 on 2017-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20171209_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
