# Generated by Django 2.0 on 2017-12-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171209_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
