# Generated by Django 2.0 on 2017-12-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20171209_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firma',
            new_name='company',
        ),
    ]
