# Generated by Django 2.0 on 2017-12-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171209_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='info',
        ),
    ]
