# Generated by Django 2.0 on 2017-12-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20171211_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visibility_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility_mail',
            field=models.BooleanField(default=True),
        ),
    ]
