# Generated by Django 2.0 on 2018-02-23 19:20

import apps.profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='info')),
                ('expert', models.BooleanField(default=False, verbose_name='expert')),
                ('visibility_mail', models.BooleanField(default=False, verbose_name='visibility of mail adress')),
                ('visibility_company', models.BooleanField(default=False, verbose_name='visibility of company')),
                ('visibility_info', models.BooleanField(default=False, verbose_name='visibility of information')),
                ('visibility_first_name', models.BooleanField(default=False, verbose_name='visibility of first name')),
                ('visibility_last_name', models.BooleanField(default=False, verbose_name='visibility of last name')),
                ('max_projects', models.IntegerField(default=5, verbose_name='maximum number of projects')),
                ('max_datarows', models.IntegerField(default=1000, verbose_name='maximum number of datarows')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=apps.profile.models.profile_image_path, verbose_name='path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile image',
                'verbose_name_plural': 'profile images',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expert',
            field=models.BooleanField(default=False, verbose_name='expert'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=1000, verbose_name='max_datarows'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_projects',
            field=models.IntegerField(default=5, verbose_name='max_projects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_company',
            field=models.BooleanField(default=False, verbose_name='visibility of company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_first_name',
            field=models.BooleanField(default=False, verbose_name='visibility_first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_info',
            field=models.BooleanField(default=False, verbose_name='visibility_info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_last_name',
            field=models.BooleanField(default=False, verbose_name='visibility_last_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_mail',
            field=models.BooleanField(default=False, verbose_name='visibility_mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=1000, verbose_name='maximum number of datarows'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_projects',
            field=models.IntegerField(default=5, verbose_name='maximum number of projects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_first_name',
            field=models.BooleanField(default=False, verbose_name='visibility of first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_info',
            field=models.BooleanField(default=False, verbose_name='visibility of information'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_last_name',
            field=models.BooleanField(default=False, verbose_name='visibility of last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_mail',
            field=models.BooleanField(default=False, verbose_name='visibility of mail adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=100000, verbose_name='maximum number of datarows'),
        ),
    ]
