# Generated by Django 2.0 on 2018-01-28 15:19

import apps.profile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='info')),
                ('expert', models.BooleanField(default=False, verbose_name='expert')),
                ('visibility_mail', models.BooleanField(default=False, verbose_name='visibility of mail adress')),
                ('visibility_company', models.BooleanField(default=False, verbose_name='visibility of company')),
                ('visibility_info', models.BooleanField(default=False, verbose_name='visibility of information')),
                ('visibility_first_name', models.BooleanField(default=False, verbose_name='visibility of first name')),
                ('visibility_last_name', models.BooleanField(default=False, verbose_name='visibility of last name')),
                ('max_projects', models.IntegerField(default=5, verbose_name='maximum number of projects')),
                ('max_datarows', models.IntegerField(default=1000, verbose_name='maximum number of datarows')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=apps.profile.models.profile_image_path, verbose_name='path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'project image',
                'verbose_name_plural': 'project images',
            },
        ),
    ]
