# Generated by Django 2.0 on 2018-01-18 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expert',
            field=models.BooleanField(default=False, verbose_name='expert'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=1000, verbose_name='max_datarows'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_projects',
            field=models.IntegerField(default=5, verbose_name='max_projects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_company',
            field=models.BooleanField(default=False, verbose_name='visibility of company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_first_name',
            field=models.BooleanField(default=False, verbose_name='visibility_first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_info',
            field=models.BooleanField(default=False, verbose_name='visibility_info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_last_name',
            field=models.BooleanField(default=False, verbose_name='visibility_last_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_mail',
            field=models.BooleanField(default=False, verbose_name='visibility_mail'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile', verbose_name='profile'),
        ),
    ]
