# Generated by Django 2.0 on 2018-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180118_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'verbose_name': 'profile image', 'verbose_name_plural': 'profile images'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=1000, verbose_name='maximum number of datarows'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_projects',
            field=models.IntegerField(default=5, verbose_name='maximum number of projects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_first_name',
            field=models.BooleanField(default=False, verbose_name='visibility of first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_info',
            field=models.BooleanField(default=False, verbose_name='visibility of information'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_last_name',
            field=models.BooleanField(default=False, verbose_name='visibility of last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visibility_mail',
            field=models.BooleanField(default=False, verbose_name='visibility of mail adress'),
        ),
    ]
