# Generated by Django 2.0 on 2018-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20180128_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_datarows',
            field=models.IntegerField(default=100000, verbose_name='maximum number of datarows'),
        ),
    ]
