# Generated by Django 2.0 on 2019-04-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiver', '0003_auto_20190408_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsServiceExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_state', models.IntegerField(default=1)),
                ('last_contact', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiver.AnalyticsService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
